packages:
  - 'packages/*'

# Define a catalog of version ranges.
catalog:
  # "react": "catalog:"
  vite: ^6.0.2
  react: ^19.0.0-rc.1
  react-dom: ^19.0.0-rc.1
  react-router: ^7.0.1
#
# multiple
# catalogs:
#   # "react": "catalog:react17"
#   react17:
#     react: ^17.0.2
#     react-dom: ^17.0.2

#   # "react": "catalog:react18"
#   react18:
#     react: ^18.2.0
#     react-dom: ^18.2.0
