packages:
  - 'apps/*'
  - 'packages/config/*'
  - 'packages/ui/*'

# Define a catalog of version ranges.
catalog:
  # "react": "catalog:"
  typescript: 5.7.3
  vite: 6.0.7
  '@vitejs/plugin-react-swc': 3.7.2
  react: 19.0.0
  '@types/react': 19.0.4
  react-dom: 19.0.0
  '@types/react-dom': 19.0.2
  react-router: 7.1.1
#
# Define a catalog of version ranges.
# catalog:
#   # "react": "catalog:"
#   react: ^19.0.0-rc.1
# multiple
# catalogs:
#   # "react": "catalog:react17"
#   react17:
#     react: ^17.0.2
#     react-dom: ^17.0.2

#   # "react": "catalog:react18"
#   react18:
#     react: ^18.2.0
#     react-dom: ^18.2.0
